master:
  build: master
  environment:
    LOG_LEVEL: debug
  hostname: master
  expose:
    - "4505"
    - "4506"
  volumes:
    - ./master/srv/salt:/srv/salt/:rw
    - ./master/master:/etc/salt/master:rw
  command: /start.sh
minion1:
  build: minion
  links:
   - master
  environment:
    MINION_ID: minion1
    SALT_GRAINS: "{'role': 'frontend'}"
    LOG_LEVEL: debug
  hostname: minion1
  command: /start.sh
minion2:
  build: minion
  links:
   - master
  environment:
    MINION_ID: minion2
    SALT_GRAINS: "{'role': 'backend'}"
    LOG_LEVEL: debug
  hostname: minion2
  command: /start.sh